//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.hideakin.textsearch.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.hideakin.textsearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyButtonContent {
            get {
                return ResourceManager.GetString("ApplyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to authenticate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthenticateFailure {
            get {
                return ResourceManager.GetString("AuthenticateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authencation has been done successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthenticateSuccess {
            get {
                return ResourceManager.GetString("AuthenticateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextSearch - Authenticate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthWindowTitle {
            get {
                return ResourceManager.GetString("AuthWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMenuItemHeader {
            get {
                return ResourceManager.GetString("EditMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Authenticate... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileAuthMenuItemHeader {
            get {
                return ResourceManager.GetString("FileAuthMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileExitMenuItemHeader {
            get {
                return ResourceManager.GetString("FileExitMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMenuItemHeader {
            get {
                return ResourceManager.GetString("FileMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpMenuItemHeader {
            get {
                return ResourceManager.GetString("HelpMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextSearch - What do you want to find today? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordLabelContent {
            get {
                return ResourceManager.GetString("PasswordLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryButtonContent {
            get {
                return ResourceManager.GetString("QueryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Phrase to find: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryLabelContent {
            get {
                return ResourceManager.GetString("QueryLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Username に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsernameLabelContent {
            get {
                return ResourceManager.GetString("UsernameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewMenuItemHeader {
            get {
                return ResourceManager.GetString("ViewMenuItemHeader", resourceCulture);
            }
        }
    }
}
